name: Validate, build, and push dev container

permissions:
  actions: read

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - 'docs/**'
      - 'src/**'
      - eleventy.config.js
      - package.json

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # this isn't strictly necessary but is recommended
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      # no checkout needed as the action uses the git context
      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check
