name: Validate, test, build, and push dev container

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - 'docs/**'
      - 'src/**'
      - eleventy.config.js
      - package.json
      - .hadolint.yaml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ukhsa-collaboration/standards-org

jobs:
  check-image:
    name: Validate the image definition
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Lint Dockerfile
        run: docker run --rm -i -v './.hadolint.yaml:/.hadolint.yaml' hadolint/hadolint < Dockerfile

      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check

  test-image:
    name: Run simple end to end tests on the dev container image
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install node dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- test/docker/container.js

  build-image:
    name: Build the image and push to GHCR
    needs: [check-image, test-image]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Tag latest
        # update latest tag to refer to this new build but only on main branch pushes
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
